# This is a configuration file that contains the deductive/theoretical codes
# that are shown in the utterance editer sub-view


[emergence]

    [emergence.emergent]
    keywords = "bottom-up, collective, self-organizing"
    conceptual_example = "Traffic jams form by each car following a simple set of rules."
    verbatim_excerpt = "{to-be-written}"

    [emergence.centralized]
    keywords = "pre-determined, god-like, top-down"
    conceptual_example = "Traffic jams form because of accidents or traffic lights."
    verbatim_excerpt = "{to-be-written}"



[stochasticity]

    [stochasticity.probabilistic]
    keywords = "random, uncertain, undetermined, chance"
    conceptual_example = "Each car has a random maximum speed."
    verbatim_excerpt = "{to-be-written}"

    [stochasticity.deterministic]
    keywords = "predictable, certain, fixed, inevitable"
    conceptual_example = "Each car has the same maximum speed."
    verbatim_excerpt = "{to-be-written}"



[levels]

    [levels.micro_and_macro]
    keywords = "level differentiation, individual to collective, local to global"
    conceptual_example = "Cars move forward, but the traffic jam moves backwards."
    verbatim_excerpt = "{to-be-written}"

    [levels.level_slippage]
    keywords = "attributing macro to micro, confusion, misattribution"
    conceptual_example = "Traffic jam moves forward because the cars move forward."
    verbatim_excerpt = "{to-be-written}"



[linearity]

    [linearity.nonlinear]
    keywords = "critical threshold, tipping point, delayed outcome, butterfly effect"
    conceptual_example = "No jams form when there are only N cars, but a jam forms when there are N+1 cars."
    verbatim_excerpt = "{to-be-written}"

    [linearity.linear]
    keywords = "proportional cause-effect, direct, immediate outcome"
    conceptual_example = "Adding one car to the road increases the size of the jam by one car."
    verbatim_excerpt = "{to-be-written}"

    [interrelatedness.feedback_loops]
    keywords = "runaway effect, dynamic equilibrium, exponential growth"
    conceptual_example = "{{ to-be-writtten-or-removed-because-non-linear-encapsulates-feedback-loops}}"
    verbatim_excerpt = "{to-be-written}"



[cognitive_load]

    [cognitive_load.small_n]
    keywords = "sparse, very few, less than five, distinct individuals"
    conceptual_example = "Adding only 2-3 cars to a traffic model."
    verbatim_excerpt = "{to-be-written}"

    [cognitive_load.mid_level]
    keywords = "manageable, not too few but not too many, small group"
    conceptual_example = "Adding 10-20 cars to a traffic model."
    verbatim_excerpt = "{to-be-written}"

    [cognitive_load.large_n]
    keywords = "lots of, plentiful, large community"
    conceptual_example = "Adding hundreds of cars to a traffic model."
    verbatim_excerpt = "{to-be-written}"

