# This is a configuration file that contains the deductive/theoretical codes
# that are shown in the utterance editer sub-view


[emergence]

    [emergence.emergent]
    description = "To-be-written soon..."
    keywords = "bottom-up, collective, self-organizing"
    conceptual_example = ""
    verbatim_excerpt = ""

    [emergence.centralized]
    description = "To-be-written soon..."
    keywords = "pre-determined, god-like, top-down"
    conceptual_example = ""
    verbatim_excerpt = ""



[stochasticity]

    [stochasticity.probabilistic]
    description = "To-be-written soon..."
    keywords = "random, uncertain, undetermined, chance"
    conceptual_example = ""
    verbatim_excerpt = ""

    [stochasticity.deterministic]
    description = "To-be-written soon..."
    keywords = "predictable, certain, fixed, inevitable"
    conceptual_example = ""
    verbatim_excerpt = ""



[levels]

    [levels.micro_and_macro]
    description = "To-be-written soon..."
    keywords = ""
    conceptual_example = ""
    verbatim_excerpt = ""

    [levels.level_slippage]
    description = "To-be-written soon..."
    keywords = ""
    conceptual_example = ""
    verbatim_excerpt = ""



[interrelatedness]

    [interrelatedness.feedback_loops]
    description = "To-be-written soon..."
    keywords = "runaway effect, dynamic equilibrium, exponential growth"
    conceptual_example = ""
    verbatim_excerpt = ""



[linearity]

    [linearity.nonlinear]
    description = "To-be-written soon..."
    keywords = "critical threshold, tipping point, delayed outcome, butterfly effect"
    conceptual_example = ""
    verbatim_excerpt = ""

    [linearity.linear]
    description = "To-be-written soon..."
    keywords = "proportional cause-effect, direct, immediate outcome"
    conceptual_example = ""
    verbatim_excerpt = ""



[cognitive_load]

    [cognitive_load.small_n]
    description = "To-be-written soon..."
    keywords = ""
    conceptual_example = ""
    verbatim_excerpt = ""

    [cognitive_load.mid_level]
    description = "To-be-written soon..."
    keywords = ""
    conceptual_example = ""
    verbatim_excerpt = ""

    [cognitive_load.large_n]
    description = "To-be-written soon..."
    keywords = ""
    conceptual_example = ""
    verbatim_excerpt = ""

